version: '3.0'
services:
    nginx:
        image: "nginx:latest"
        ports:
            - "80:80"
            - "8080:8080"            
        volumes:
            - ./wwwroot:/var/www/html
            - ./configs/nginx:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
        networks:
            - webnet
    php-fpm:
        image: "myphp72"
        volumes:
            - ./wwwroot:/var/www/html
        networks:
            - webnet
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
        - ./db/mysql:/var/lib/mysql
        - ./tmp/mysqld:/var/run/mysqld
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=root
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0
        networks:
            - webnet
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        networks:
            - webnet


networks:
    webnet: